### PR TITLE
Setup unit testing(Jest)

### PR DESCRIPTION
**Pull request by atran25**
- Setup unit testing via Jest [https://jestjs.io/docs/getting-started](url)
- Created a new MongoDB database for testing purposes, found on the same account as production database
- Created a sample test for the reservations api

### CODE REVIEW

**Comment by martinn8145** [comment]
lgtm, but it was already working for me before this commit, so wait on others to comment before merge.

**Comment by martinn8145** [comment]
lgtm

**Comment by jonathanSeang** [comment]
looks great

**Comment by cmtnguyen** [comment]
good to go!

**Pull request merged**
