### PR TITLE
Added more test cases to API routes

### PR DESCRIPTION
**Pull request by atran25**
Done:
- Comments added to each API route in reservations
- Added error handling to each API route in reservations
- Added test cases for the 2 new API routes (start/end date, checkedIn)
- Added error handling test cases to all API routes in reservations

To Do:
- Delete unneeded reports model and API route
-  Create test cases for user API route

### CODE REVIEW

**Comment by johnpaultran** [comment]
amazing

**Comment by cmtnguyen** [comment]
lgtm

**Comment by atran25** [comment]
Done:
- Delete unneeded reports model and API route
- Create test cases for user API route

To Do:
- None

**Comment by martinn8145** [comment]
Great work!

**Comment by jonathanSeang** [comment]
looks great!

**Pull request merged**
